# Generated by Django 4.0.4 on 2022-07-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menti',
            name='status',
            field=models.CharField(choices=[('start', 'start'), ('end', 'end')], default=2, max_length=100),
        ),
        migrations.AlterField(
            model_name='menti',
            name='users_joined',
            field=models.IntegerField(default=0),
        ),
    ]
