# Generated by Django 4.0.4 on 2022-07-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_menti_status_alter_menti_users_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menti',
            name='status',
            field=models.CharField(choices=[('start', 'start'), ('end', 'end')], default=0, max_length=100),
        ),
    ]
