# Generated by Django 4.0.4 on 2022-07-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_menti_current_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menti',
            name='current_question',
        ),
    ]
